### PR TITLE
Update to Pkg3 (Project.toml, Manifest.toml)

### PR DESCRIPTION
**Pull request by OliverEvans96**
This makes it possible to use some nice features from Pkg3, including `]test`.

### CODE REVIEW

**Comment by blegat** [comment]
Last time I checked, it is not time yet to replace the REQUIRE file by Project and Manifest, correct me if I am wrong. `] test Polyhedra` should work.

**Comment by OliverEvans96** [comment]
I'm not sure what the official migration plan is, but as far as I can tell, all of the features of require are available now via Project and Manifest, including test-specific dependencies.

You're right, `]test Polyhedra` works, but

```
(v1.1) pkg> activate .

(Polyhedra) pkg> test
ERROR: trying to test unnamed project
```

Not a huge deal, but this feature works in the Project/Manifest paradigm.

**Comment by OliverEvans96** [comment]
Also, I'm not sure what the implications are from the perspective of METADATA/General Registry.

 Looking at a few other packages, it seems that the community hasn't really transitioned. E.g. [JuMP](https://github.com/JuliaOpt/JuMP.jl) and [DifferentialEquations](https://github.com/JuliaDiffEq/DifferentialEquations.jl) only use require, but it also seems possible to use both, e.g. [Flux](https://github.com/FluxML/Flux.jl).

**Comment by blegat** [comment]
I think using both is authorized but you need to keep a REQUIRE file to be able to tag new versions to METADATA

**Comment by OliverEvans96** [comment]
Ah, that makes sense. How's this, then?

**Comment by blegat** [comment]
Looks like it is needed now: https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677/30
and we can get rid of REQUIRE

**Comment by blegat** [comment]
Merged manually

**Pull request closed without merging**
