### PR TITLE
WIP: Fix v0.6 compatibility

### PR DESCRIPTION
**Pull request by rdeits**
Companion to https://github.com/JuliaPolyhedra/CDDLib.jl/pull/14 (each PR requires the other, since the tests are circularly dependent). 

Due to some breaking changes in GeometryTypes and StaticArrays, this makes Polyhedra.jl v0.6-only.

### CODE REVIEW

**Comment by rdeits** [comment]
merging in master broke some more things...this isn't quite ready

**Comment by blegat** [comment]
Thanks a lot ! It looks great :)
The next release v0.2.0 will be v0.6 only which will allow to simplify a few thinks.

**Comment by rdeits** [comment]
Related: https://github.com/JuliaGeometry/GeometryTypes.jl/issues/89

**Comment by rdeits** [comment]
Another issue came up while I was trying to get LRSLib.jl working. Polyhedra.jl has a `getlibraryfor` method that tries to dynamically import a polyhedra library in the same way the JuMP used to import solvers. Given that JuMP ended up getting rid of that functionality for v0.6, we might have to do the same. 

I've always specified the library explicitly in my code (I didn't even know this mechanism existed). @blegat is this something you've relied on?

**Comment by rdeits** [comment]
The specific reason this issue came up when testing LRSLib is:

* Polyhedra's `basictests.jl` line 13 tries to do `Polyhedron{2, Float64}(p)`
* LRSLib only implements `getlibraryfor()` for `Integer` and `Rational` types
* so Polyhedra's `src/default.jl` dynamically loads `CDDLib` to do the conversion
* but now CDDLib is in the future, so it can't be used from the current context
* so we get world age errors

I think that maybe the right thing to do is to (a) get rid of the runtime loading in default.jl and (b) only try to convert to `Polyhedron{2, Float64}` for libraries which support floating-point polyhedra.

**Comment by blegat** [comment]
I would agree to remove the default choosing mechanism since it no longer works but I would still like to keep `getlibraryfor` so that we can do
```julia
[1.0 2.0; 1.5 2.5] * p
```
where `p` is a `LRSLibrary`.
It should call `getlibraryfor(::LRSPolyhedron, ::Type{Val{N}}, ::Type{BigFloat})` which is not caught by `LRSLibrary` so `Polyhedra` needs to do something !
Another example is 2D only libraries like [CHull2d.jl](https://github.com/cc7768/CHull2d.jl). which will implement `getlibraryfor(::CHull2dPolyhedron, ::Type{Val{2}}, ::Type{T}}` so it needs a fallback for other dimensions it case it gets lifted.
I replacing the current mechanism by the following:
```julia
getlibraryfor{N, T}(::Val{N}, ::Type{T}) = SimplePolyhedron{N, T}
```
Polyhedra have default implementations for almost every operation. These operations are usually reimplemented for speed by the libraries but `SimplePolyhedron` is the laziest of all. It lets `Polyhedra` do all the job ! I have implemented a naive version for the [double description](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/src/doubledescription.jl) a few days ago so now `SimplePolyhedron` even supports representation conversion :)
It is missing the adjacency relations between the vertices to be as fast as CDD and ConvexHull.jl but currently adjacency info is not stored in the H-representation but it might be in the future :-P

**Comment by rdeits** [comment]
Ok, that sounds great!

By the way, do you mean something like:

```julia
getlibraryfor{N, T}(::Val{N}, ::Type{T}) = SimplePolyhedronLibrary()
```

since I assume `getlibraryfor` should return a library, not a polyhedron?

**Comment by blegat** [comment]
Yes that is what I meant :)

**Comment by rdeits** [comment]
Ok, got it. 

I'm now getting the following error from the tests:

```julia
Doc example tests in exact arithmetic with LRSLib.LRSLibrary: Error During Test
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching vrepiscomputed(::Polyhedra.LiftedHRepresentation{1,Float64})
  Closest candidates are:
    vrepiscomputed(::Polyhedra.SimplePolyhedron) at /home/rdeits/.julia/v0.6/Polyhedra/src/simplepolyhedron.jl:80
    vrepiscomputed(::CDDLib.CDDPolyhedron) at /home/rdeits/.julia/v0.6/CDDLib/src/polyhedron.jl:190
    vrepiscomputed(::LRSLib.LRSPolyhedron) at /home/rdeits/.julia/v0.6/LRSLib/src/polyhedron.jl:152
    ...
  Stacktrace:
   [1] defaultLPsolverfor at /home/rdeits/.julia/v0.6/Polyhedra/src/default.jl:4 [inlined] (repeats 2 times)
   [2] gethredundantindices(::Polyhedra.LiftedHRepresentation{1,Float64}) at /home/rdeits/.julia/v0.6/Polyhedra/src/redundancy.jl:24
   [3] removehredundancy! at /home/rdeits/.julia/v0.6/Polyhedra/src/simplepolyhedron.jl:114 [inlined]
   [4] inequality_fulltest(::Polyhedra.SimplePolyhedron{1,Float64}, ::Array{Int64,1}, ::Array{Int64,1}, ::IntSet) at /home/rdeits/.julia/v0.6/Polyhedra/test/utils.jl:69
   [5] doctest(::LRSLib.LRSLibrary) at /home/rdeits/.julia/v0.6/Polyhedra/test/docexample.jl:29
```

should `vrepiscomputed(::LiftedHRepresentation)` just be `false`?

**Comment by blegat** [comment]
`vrepiscomputed` shouldn't be called on a `Representation`. We should rather add the followign in `default.jl`
```julia
defaultLPsolverfor(::VRepresentation, solver=JuMP.UnsetSolver()) = SimpleVRepSolver()
defaultLPsolverfor(::HRepresentation, solver=JuMP.UnsetSolver()) = solver
```

**Comment by rdeits** [comment]
ok, done, thanks

**Comment by blegat** [comment]
I am improving `SimplePolyhedron` to make the tests pass

**Comment by rdeits** [comment]
Ok, great! I'm working on getting GeometryTypes/Meshing/etc. up and running as well.

**Comment by blegat** [comment]
Superseded by #30

**Comment by blegat** [comment]
I am looking forward to it, I will need to do plotting soon :)

**Pull request closed without merging**
