### PR TITLE
Update Documenter to v0.27

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by schillic** [comment]
@blegat We have the same segmentation fault in a package. Would be great if you figure it out for us :sweat_smile:

**Comment by blegat** [comment]
I have opened an issue here: https://github.com/jheinen/GR.jl/issues/422 as the segfault seems to be in the GR library. Let's try to fix Literate to an older version.

**Comment by schillic** [comment]
I delta debugged a bit and the problem occurs when calling `plot` from within `Literate` (using the default `GR` but I did not try out other backends). Not sure where exactly the problem is yet.

**Comment by schillic** [comment]
I found the solution (at least for us) here: https://github.com/JuliaPlots/Plots.jl/issues/3650

Just add the change in the linked commits at the bottom: specifically you can add `GKSwstype: nul` to `env` in the "Build and deploy" section of `.github/docs.yml`. Or, what I did, add ` ENV["GKSwstype"] = "100"` to `docs/make.jl`.

**Pull request merged**
